{
  "formatVersion" : "1.1",
  "createdBy" : {
    "gradle" : {
      "version" : "7.4.1"
    }
  },
  "component" : {
    "group" : "com.github.Blatzar",
    "module" : "NiceHttp",
    "version" : "0.4.11",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "org.jsoup",
      "module" : "jsoup",
      "version" : {
        "requires" : "1.17.2"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp-dnsoverhttps",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    } ],
    "files" : [ {
      "name" : "NiceHttp-0.4.11.jar",
      "url" : "NiceHttp-0.4.11.jar",
      "size" : 45485,
      "sha512" : "22ee2c13803f7f0435b60a9af8cef6d72505640666320f803f8514f95c2df05a3d423fbeedfdafcc604ab5c2aad372f599a637a8e707950b580752e125f174f9",
      "sha256" : "7983cf5110a24538aa4ab451ed8736d19092c8e354354abf1a9b1a0886360c8b",
      "sha1" : "11ac4566d7b115560e6eb8acdbee5e4b3d21607b",
      "md5" : "02e66c98c6bd203b7a75b6277870e1bb"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "8",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlinx",
      "module" : "kotlinx-coroutines-core",
      "version" : {
        "requires" : "1.7.1"
      }
    }, {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib-jdk8",
      "version" : {
        "requires" : "1.9.22"
      }
    }, {
      "group" : "org.json",
      "module" : "json",
      "version" : {
        "requires" : "20231013"
      }
    }, {
      "group" : "org.jsoup",
      "module" : "jsoup",
      "version" : {
        "requires" : "1.17.2"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    }, {
      "group" : "com.squareup.okhttp3",
      "module" : "okhttp-dnsoverhttps",
      "version" : {
        "requires" : "5.0.0-alpha.12"
      }
    } ],
    "files" : [ {
      "name" : "NiceHttp-0.4.11.jar",
      "url" : "NiceHttp-0.4.11.jar",
      "size" : 45485,
      "sha512" : "22ee2c13803f7f0435b60a9af8cef6d72505640666320f803f8514f95c2df05a3d423fbeedfdafcc604ab5c2aad372f599a637a8e707950b580752e125f174f9",
      "sha256" : "7983cf5110a24538aa4ab451ed8736d19092c8e354354abf1a9b1a0886360c8b",
      "sha1" : "11ac4566d7b115560e6eb8acdbee5e4b3d21607b",
      "md5" : "02e66c98c6bd203b7a75b6277870e1bb"
    } ]
  } ]
}