{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.recloudstream.gradle",
    "module" : "gradle",
    "version" : "81b1d424d2",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.9"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "files" : [ {
      "name" : "gradle-81b1d424d2.jar",
      "url" : "gradle-81b1d424d2.jar",
      "size" : 63734,
      "sha512" : "d6bacc4af68108ddd82378f52fff7a0598c692bf0b2ef7de230bb3b2b3b4dea19b81d8830778565a35affd5dd5f6b6a75ae23a4358700e180840f6acc295c8e8",
      "sha256" : "9bcd93a34448898645fef86a5eca92b4f6de668c70be3cc636f92081a13778ee",
      "sha1" : "461de3a422edde30d21f2a08bc3ee690dd155090",
      "md5" : "95341afe88870fd7d1b1a330d811e134"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "11",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "org.jetbrains.kotlin",
      "module" : "kotlin-stdlib",
      "version" : {
        "requires" : "2.0.0"
      }
    }, {
      "group" : "org.ow2.asm",
      "module" : "asm",
      "version" : {
        "requires" : "9.4"
      }
    }, {
      "group" : "org.ow2.asm",
      "module" : "asm-tree",
      "version" : {
        "requires" : "9.4"
      }
    } ],
    "files" : [ {
      "name" : "gradle-81b1d424d2.jar",
      "url" : "gradle-81b1d424d2.jar",
      "size" : 63734,
      "sha512" : "d6bacc4af68108ddd82378f52fff7a0598c692bf0b2ef7de230bb3b2b3b4dea19b81d8830778565a35affd5dd5f6b6a75ae23a4358700e180840f6acc295c8e8",
      "sha256" : "9bcd93a34448898645fef86a5eca92b4f6de668c70be3cc636f92081a13778ee",
      "sha1" : "461de3a422edde30d21f2a08bc3ee690dd155090",
      "md5" : "95341afe88870fd7d1b1a330d811e134"
    } ]
  } ]
}
